fixed many launcher stuff

diff --git a/scripts/launcher b/scripts/launcher
--- a/scripts/launcher
+++ b/scripts/launcher
@@ -84,7 +84,7 @@ echo -e "${RED}
 }
 
 # Preset Chain Config URLs
-PRESETS=("starknet_mainnet" "starknet_testnet" "test" "devnet")
+PRESETS=("starknet_mainnet" "starknet_testnet" "devnet")
 PRESET_URLS=(
   "https://raw.githubusercontent.com/madara-alliance/madara/main/configs/presets/mainnet.yaml"
   "https://raw.githubusercontent.com/madara-alliance/madara/main/configs/presets/testnet.yaml"
@@ -330,7 +330,7 @@ tput ed
 echo -e "\n${GREEN}Your node has been correctly named: ${BOLD}${NODE_NAME}${NC}${GREEN}.${NC}"
 
 # Ask for the database path
-echo -e "\n💾 ${YELLOW}${BOLD}Where would you like to store your database?${NC}${YELLOW} (it will be located inside your docker container) (default: /tmp/madara)${NC}"
+echo -e "\n💾 ${YELLOW}${BOLD}Where would you like to store your database?${NC}${YELLOW} (it will be mapped to /data inside your container) (default: /tmp/madara)${NC}"
 read -p "> " BASE_PATH
 BASE_PATH=${BASE_PATH:-/tmp/madara}
 
@@ -472,6 +472,40 @@ if [ "$MODE" == "sequencer" ] || [ "$MODE" == "devnet" ]; then
             *) echo -e "${YELLOW}Invalid choice, please enter 1, 2, 3, or 4.${NC}"; continue ;;
         esac
 
+        OVERRIDE_DEVNET_CHAIN_ID="false"
+        if [ "$MODE" == "devnet" ] && { [ "$PRESET" == "starknet_mainnet" ] || [ "$PRESET" == "starknet_testnet" ]; }; then
+            echo -e "\n❗ You're running a devnet with the network config of \"${PRESET}\". This means that devnet transactions can be replayed on the actual network."
+            echo -e "\n${YELLOW}Do you want to proceed or use the devnet chain config instead?${NC}"
+            echo -e "${YELLOW}1. Switch to devnet config (recomended)${NC}"
+            echo -e "${YELLOW}2. Continue with ${PRESET} chain config${NC}"
+            while true; do
+                read -p "> " USER_CHOICE
+                case $USER_CHOICE in
+                    1)
+                        # Switch to devnet config
+                        PRESET="${PRESETS[2]}" # "devnet" at index 2
+                        PRESET_URL="${PRESET_URLS[2]}"
+                        # Re-download the devnet chain config
+                        PRESET_PATH=$(mktemp)
+                        curl -s -o "$PRESET_PATH" "$PRESET_URL"
+                        if [ $? -ne 0 ] || [ ! -s "$PRESET_PATH" ]; then
+                            echo -e "${RED}Failed to download the chain config file from $PRESET_URL.${NC}"
+                            exit 1
+                        fi
+                        break
+                        ;;
+                    2)
+                        # Continue with the current configuration
+                        OVERRIDE_DEVNET_CHAIN_ID="true"
+                        break
+                        ;;
+                    *)
+                        echo -e "${YELLOW}Invalid choice. Please enter 1 or 2.${NC}"
+                        ;;
+                esac
+            done
+        fi
+
         # Now, if a preset was selected (options 1-3), download the chain config file
         if [ "$PRESET" != "custom" ]; then
             # Download the chain config file to a temporary location
@@ -482,7 +516,6 @@ if [ "$MODE" == "sequencer" ] || [ "$MODE" == "devnet" ]; then
                 exit 1
             fi
         fi
-
 
         # Call modify_chain_config with the chain config file
         modify_chain_config "$PRESET_PATH"
@@ -500,18 +533,18 @@ else
         case $NETWORK_CHOICE in
             1)
                 NETWORK="mainnet"
-                PRESET="starknet_mainnet"
-                PRESET_URL="${PRESET_URLS[$PRESET]}"
+                PRESET="${PRESETS[0]}"
+                PRESET_URL="${PRESET_URLS[0]}"
                 ;;
             2)
                 NETWORK="testnet"
-                PRESET="starknet_testnet"
-                PRESET_URL="${PRESET_URLS[$PRESET]}"
+                PRESET="${PRESETS[1]}"
+                PRESET_URL="${PRESET_URLS[1]}"
                 ;;
             3)
                 NETWORK="test"
-                PRESET="test"
-                PRESET_URL="${PRESET_URLS[$PRESET]}"
+                PRESET="${PRESETS[2]}"
+                PRESET_URL="${PRESET_URLS[2]}"
                 ;;
             4)
                 echo -e "\n${YELLOW}Please provide the path to your custom chain config:${NC}"
@@ -563,7 +596,7 @@ tput ed
 
 if [ "$RPC_ACCESS" == "yes" ]; then
     RPC_OPTS="--rpc-cors '*' --rpc-external"
-    echo -e "\n🚪 ${YELLOW}${BOLD}On which port do you want RPC access? (default: 9944)${NC}"
+    echo -e "\n🚪 ${YELLOW}${BOLD}On which port do you want RPC access? (it will be mapped to the same port inside your container) (default: 9944)${NC}"
     
     while true; do
         read -p "> " RPC_PORT
@@ -595,15 +628,17 @@ tput rc
 tput ed
 
 # Ask for the L1 endpoint URL
-while true; do
-    echo -e "\n🔗 ${YELLOW}${BOLD}Provide an L1 RPC endpoint (URL format):${NC}"
-    read -p "> " L1_ENDPOINT
-    if [[ $L1_ENDPOINT =~ ^https?:// ]]; then
-        break
-    else
-        echo -e "${RED}Please enter a valid URL starting with http:// or https://.${NC}"
-    fi
-done
+if [ "$MODE" == "full" ] || [ "$MODE" == "sequencer" ]; then
+    while true; do
+        echo -e "\n🔗 ${YELLOW}${BOLD}Provide an L1 RPC endpoint (URL format):${NC}"
+        read -p "> " L1_ENDPOINT
+        if [[ $L1_ENDPOINT =~ ^https?:// ]]; then
+            break
+        else
+            echo -e "${RED}Please enter a valid URL starting with http:// or https://.${NC}"
+        fi
+    done
+fi
 
 tput rc
 tput ed
@@ -619,19 +654,27 @@ fi
 
 # Build the final Docker run command
 if [ "$MODE" == "full" ] && [ "$CONFIG_MODIFIED" == "false" ] && [ "$NETWORK" != "custom" ]; then
-    # Use --network option
     DOCKER_COMMAND="docker run -d --name madara-client \
         -v ${BASE_PATH}:/data \
         ${PORT_MAPPING} \
         $IMAGE_NAME \
         --${MODE} --name \"${NODE_NAME}\" --network \"${NETWORK}\" --base-path=\"/data\" ${RPC_OPTS} --l1-endpoint \"${L1_ENDPOINT}\""
 else
-    # Use --chain-config-path option
     DOCKER_COMMAND="docker run -d --name madara-client \
         -v ${BASE_PATH}:/data \
         ${PORT_MAPPING} \
         $IMAGE_NAME \
-        --${MODE} --name \"${NODE_NAME}\" --chain-config-path=\"/data/chain_config.yaml\" --base-path=\"/data\" ${RPC_OPTS} --l1-endpoint \"${L1_ENDPOINT}\""
+        --${MODE} --name \"${NODE_NAME}\" --chain-config-path=\"/data/chain_config.yaml\" --base-path=\"/data\" ${RPC_OPTS}"
+
+    # Add --override-devnet-chain-id if applicable
+    if [ "$OVERRIDE_DEVNET_CHAIN_ID" == "true" ]; then
+        DOCKER_COMMAND="$DOCKER_COMMAND --override-devnet-chain-id"
+    fi
+
+    # Add --l1-endpoint if applicable
+    if [ "$MODE" == "sequencer" ]; then
+        DOCKER_COMMAND="$DOCKER_COMMAND --l1-endpoint \"${L1_ENDPOINT}\""
+    fi
 fi
 
 echo -e "\n${GREEN}Your docker image is ready to be used.${NC}"
